// import React from 'react';
// import Star from './star';

export const Users = [
    {
        "id": 1,
        "moviename": "奧本海默",
        "date": "2023-07-21",
        "staravg": "",
        "star": "",
        "counter": "",
        "poster": "https://movies.yahoo.com.tw/i/r/w420/production/movies/May2023/Qc1HYHrRQcOf5Vc49EK2-1024x1622.jpg",
        "comment": ["Tracy: 評論評論評論評論評論評論評論評論", "Annie: 內容內容內容內容", "Lily: 愛睡覺愛睡覺愛睡覺", "芋頭: 已放棄已放棄已放棄已放棄已放棄已放棄已放棄已放棄已放棄", "大頭: 天天向上!!!!!!!", "西瓜: GOOOOOOOOD"],
    },
    {
        "id": 2,
        "moviename": "我的婆婆怎麼把oo搞丟了",
        "date": "2023-01-23",
        "staravg": "",
        "star": "",
        "counter": "",
        "poster": "https://i.imgur.com/A3htd3oh.jpg",
        "comment": ["Tracy: 評論評論評論評論評論評論評論評論", "Annie: 內容內容內容內容", "Lily: 愛睡覺愛睡覺愛睡覺", "Tracy: 評論評論評論評論評論評論評論評論"],
    },
    {
        "id": 3,
        "moviename": "小美人魚",
        "date": "2023-05-23",
        "staravg": "",
        "star": "",
        "counter": "",
        "poster": "https://th.bing.com/th/id/OIP.H-BEd4HOljXZXAe9JPONdgHaK9?pid=ImgDet&rs=1",
        "comment": ["Tracy: 評論評論評論評論評論評論評論評論", "Annie: 內容內容內容內容", "Lily: 愛睡覺愛睡覺愛睡覺", "Tracy: 評論評論評論評論評論評論評論評論"],
    },
    {
        "id": 4,
        "moviename": "私刑教育3",
        "date": "2023-08-31",
        "staravg": "",
        "star": "",
        "counter": "",
        "poster": "https://th.bing.com/th/id/OIF.DqGOGmSJMuBkLyFZVZhEAA?pid=ImgDet&rs=1",
        "comment": ["Tracy: 評論評論評論評論評論評論評論評論", "Annie: 內容內容內容內容", "Lily: 愛睡覺愛睡覺愛睡覺", "Tracy: 評論評論評論評論評論評論評論評論"],
    },
    {
        "id": 5,
        "moviename": "芭比",
        "date": "2023-07-21",
        "staravg": "",
        "star": "",
        "counter": "",
        "poster": "https://www.barbiemovie.com.tw/assets/images/fullbanner.jpg",
        "comment": ["Annie: 內容內容內容內容", "Lily: 愛睡覺愛睡覺愛睡覺", "Tracy: 評論評論評論評論評論評論評論評論"],
    },
    {
        "id": 6,
        "moviename": "復仇狗聯盟",
        "date": "2023-08-18",
        "staravg": "",
        "star": "",
        "counter": "",
        "poster": "https://image.agentm.tw/images/movie/ab03947f6a6a1c1a48443c62e8cf3d35e499616c9265a09ab8af7f5ed4f45a56/poster/image/px_0001.jpg",
        "comment": ["Annie: 內容內容內容內容", "Lily: 愛睡覺愛睡覺愛睡覺", "Tracy: 評論評論評論評論評論評論評論評論"],
    },
    {
        "id": 7,
        "moviename": "我的麻吉4個鬼",
        "date": "2023-07-01",
        "staravg": "",
        "star": "",
        "counter": "",
        "poster": "https://th.bing.com/th/id/OIP.hgWXYzqyFvsY12sNjhZKUAHaKk?pid=ImgDet&rs=1",
        "comment": ["Annie: 內容內容內容內容", "Lily: 愛睡覺愛睡覺愛睡覺", "Tracy: 評論評論評論評論評論評論評論評論"],
    },
    {
        "id": 8,
        "moviename": "千輝同學未免甜得過火",
        "date": "2023-08-18",
        "staravg": "",
        "star": "",
        "counter": "",
        "poster": "https://th.bing.com/th/id/OIP.5gbLkmGg9TctCQee73SUlQAAAA?pid=ImgDet&rs=1",
        "comment": ["Annie: 內容內容內容內容", "Lily: 愛睡覺愛睡覺愛睡覺", "Tracy: 評論評論評論評論評論評論評論評論"],
    },
    {
        "id": 9,
        "moviename": "我和喵喵的冒險旅行",
        "date": "2023-08-18",
        "staravg": "",
        "star": "",
        "counter": "",
        "poster": "https://th.bing.com/th/id/OIP.aLi3PJNWH2Kx6u_kUBkVCgHaKe?pid=ImgDet&rs=1",
        "comment": ["Annie: 內容內容內容內容", "Lily: 愛睡覺愛睡覺愛睡覺", "Tracy: 評論評論評論評論評論評論評論評論"],
    },
    {
        "id": 10,
        "moviename": "呼叫愛美子",
        "date": "2021-08-18",
        "staravg": "",
        "star": "",
        "counter": "",
        "poster": "https://movie-chill.tw/movie-img/x16885044183xghfq.jpg.pagespeed.ic.7nn2l72CYu.jpg",
        "comment": ["Annie: 內容內容內容內容", "Lily: 愛睡覺愛睡覺愛睡覺", "Tracy: 評論評論評論評論評論評論評論評論"],
    },
    {
        "id": 11,
        "moviename": "來自雪國的遺書",
        "date": "2020-08-18",
        "staravg": "",
        "star": "",
        "counter": "",
        "poster": "https://assets.wmoov.com/movie/photo/202304/Fragments_Keyart_1682337437.jpg",
        "comment": ["Annie: 內容內容內容內容內容內容內容內容內容內容內容內容123456內容內容", "Lily: 愛睡覺愛睡覺愛睡覺", "Tracy: 評論評論評論評論評論評論評論評論"],
    },
    {
        "id": 12,
        "moviename": "請問，還有哪裡需要加強",
        "date": "2022-07-26",
        "staravg": "",
        "star": "",
        "counter": "",
        "poster": "https://movies.yahoo.com.tw/i/r/w420/production/movies/May2023/U1Owe8cmZwiVMViRlDTa-1080x1542.jpg",
        "comment": ["Annie: 寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文寫作文", "Lily: 愛睡覺愛睡覺愛睡覺", "Tracy: 評論評論評論評論評論評論評論評論"],
    },
]